.TH "/home/enichy/Documents/Doxygene/CSFML_DOC/Documentation/basic_part/first_example/main.c" 3 "Mon Feb 5 2024" "Version 1.0" "QuickStart CSFML by Enichy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/enichy/Documents/Doxygene/CSFML_DOC/Documentation/basic_part/first_example/main.c \- This is the main file of the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.h>\fP
.br
\fC#include <SFML/Window\&.h>\fP
.br
\fC#include <SFML/System\&.h>\fP
.br
\fC#include <SFML/Audio\&.h>\fP
.br
\fC#include <SFML/Network\&.h>\fP
.br
\fC#include <SFML/Config\&.h>\fP
.br
\fC#include <SFML/OpenGL\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreate_window\fP (void)"
.br
.RI "Creates a window using CSFML library\&. "
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the main file of the program\&. 

This file contains the main function which is the entry point of the program\&. It calls the create_window function and returns 0\&. 
.SH "Function Documentation"
.PP 
.SS "void create_window (void)"

.PP
Creates a window using CSFML library\&. This function creates a window with the specified dimensions and title using the CSFML library\&. The window remains open until it is closed by the user\&.
.PP
\fBParameters\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QuickStart CSFML by Enichy from the source code\&.
